// 分析模板库 - 涵盖常见业务场景

export type TemplateCategory =
  | 'growth'
  | 'retention'
  | 'revenue'
  | 'conversion'
  | 'operations'
  | 'ecommerce'
  | 'finance'
  | 'content'
  | 'saas'
  | 'marketing'
  | 'product'
  | 'hr'
  | 'general'

export interface AnalysisTemplate {
  id: string
  name: string
  icon: string         // lucide-react icon name
  description: string
  category: TemplateCategory
  categoryLabel: string
  dataRequirements: string
  sampleQuestion: string
  color: string
  bgColor: string
}

export const CATEGORY_LABELS: Record<TemplateCategory, string> = {
  growth:     '增长分析',
  retention:  '留存分析',
  revenue:    '收入分析',
  conversion: '转化漏斗',
  operations: '运营效率',
  ecommerce:  '电商分析',
  finance:    '财务分析',
  content:    '内容流量',
  saas:       'SaaS 指标',
  marketing:  '营销分析',
  product:    '产品分析',
  hr:         '人员管理',
  general:    '通用分析',
}

export const ANALYSIS_TEMPLATES: AnalysisTemplate[] = [

  // ── 增长 ──────────────────────────────────────────────────────────────────
  {
    id: 'user_growth_trend',
    name: '用户增长趋势',
    icon: 'TrendingUp',
    description: '新增用户随时间的增长走势',
    category: 'growth',
    categoryLabel: '增长分析',
    dataRequirements: '需要包含用户注册时间或创建时间字段的表格',
    sampleQuestion: '分析最近30天每天的新增用户数量，展示增长趋势',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
  },
  {
    id: 'dau_wau_mau',
    name: 'DAU/WAU/MAU',
    icon: 'Users',
    description: '日/周/月活跃用户数统计',
    category: 'growth',
    categoryLabel: '增长分析',
    dataRequirements: '需要包含用户ID和活跃时间的行为日志表',
    sampleQuestion: '统计最近30天的日活跃用户数（DAU），并计算月活（MAU）和日活月活比',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
  },
  {
    id: 'new_user_acquisition',
    name: '用户获取分析',
    icon: 'UserPlus',
    description: '各来源渠道带来的新用户数量',
    category: 'growth',
    categoryLabel: '增长分析',
    dataRequirements: '需要包含用户来源渠道或推广来源字段的用户表',
    sampleQuestion: '按来源渠道统计新用户数量，对比各渠道的获客效果',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
  },
  {
    id: 'growth_rate',
    name: '增长率对比',
    icon: 'BarChart3',
    description: '周/月环比增长率分析',
    category: 'growth',
    categoryLabel: '增长分析',
    dataRequirements: '需要包含时间字段和数值指标的表格',
    sampleQuestion: '计算最近3个月的用户数、收入环比增长率，并与上季度对比',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
  },

  // ── 留存 ──────────────────────────────────────────────────────────────────
  {
    id: 'user_retention',
    name: '用户留存率',
    icon: 'Repeat',
    description: 'D1/D7/D30 留存率分析',
    category: 'retention',
    categoryLabel: '留存分析',
    dataRequirements: '需要包含用户ID和活跃时间的行为日志',
    sampleQuestion: '计算用户的次日留存率（D1）、7日留存率（D7）和30日留存率（D30）',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  {
    id: 'churn_analysis',
    name: '流失分析',
    icon: 'UserMinus',
    description: '用户流失率和流失原因分析',
    category: 'retention',
    categoryLabel: '留存分析',
    dataRequirements: '需要包含用户ID、最后活跃时间的表格',
    sampleQuestion: '分析近90天内流失的用户比例，流失定义为超过30天未活跃',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  {
    id: 'cohort_retention',
    name: '同期群留存',
    icon: 'Grid3x3',
    description: '按注册月份分组的留存热力图',
    category: 'retention',
    categoryLabel: '留存分析',
    dataRequirements: '需要用户注册时间和活跃记录，可追踪每个月注册用户的后续活跃',
    sampleQuestion: '生成同期群分析：按注册月份分组，查看各月用户在后续每月的留存情况',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  {
    id: 'reactivation',
    name: '用户召回分析',
    icon: 'RefreshCw',
    description: '流失用户重新激活的效果',
    category: 'retention',
    categoryLabel: '留存分析',
    dataRequirements: '需要用户流失记录和重新活跃的时间戳，或召回活动的参与数据',
    sampleQuestion: '分析最近一次召回活动的效果：召回了多少流失用户，召回后7天留存如何',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },

  // ── 收入 ──────────────────────────────────────────────────────────────────
  {
    id: 'revenue_trend',
    name: '收入趋势',
    icon: 'DollarSign',
    description: '收入随时间的变化趋势',
    category: 'revenue',
    categoryLabel: '收入分析',
    dataRequirements: '需要包含金额/收入字段和时间字段的订单或收入记录表',
    sampleQuestion: '统计最近6个月每月的总收入，展示收入趋势和环比增长率',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  {
    id: 'arpu_arppu',
    name: 'ARPU/ARPPU',
    icon: 'Activity',
    description: '人均收入和付费用户人均收入',
    category: 'revenue',
    categoryLabel: '收入分析',
    dataRequirements: '需要包含用户ID和付款金额的交易记录表',
    sampleQuestion: '计算过去30天的ARPU（每活跃用户平均收入）和ARPPU（每付费用户平均收入）',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  {
    id: 'ltv_analysis',
    name: '用户 LTV 分析',
    icon: 'TrendingUp',
    description: '用户生命周期价值估算',
    category: 'revenue',
    categoryLabel: '收入分析',
    dataRequirements: '需要包含用户ID、购买时间和金额的历史交易记录',
    sampleQuestion: '按注册渠道统计用户的累计消费金额（LTV），找出高价值用户来源',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  {
    id: 'payment_distribution',
    name: '付款金额分布',
    icon: 'BarChart3',
    description: '用户付款金额的区间分布',
    category: 'revenue',
    categoryLabel: '收入分析',
    dataRequirements: '需要包含每笔交易金额的订单或支付记录表',
    sampleQuestion: '分析用户付款金额的分布：0-100、100-500、500-2000、2000以上各区间的用户占比',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },

  // ── 转化 ──────────────────────────────────────────────────────────────────
  {
    id: 'conversion_funnel',
    name: '转化漏斗',
    icon: 'Filter',
    description: '各步骤的转化率和流失情况',
    category: 'conversion',
    categoryLabel: '转化漏斗',
    dataRequirements: '需要包含用户行为事件或操作步骤的日志表',
    sampleQuestion: '分析用户从注册到首次付款的转化漏斗，计算每步的转化率',
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },
  {
    id: 'signup_conversion',
    name: '注册转化分析',
    icon: 'LogIn',
    description: '访客到注册用户的转化率',
    category: 'conversion',
    categoryLabel: '转化漏斗',
    dataRequirements: '需要包含访问/注册事件和时间戳的行为日志',
    sampleQuestion: '分析最近7天每天的注册转化率，即注册用户数/访问用户数',
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },
  {
    id: 'purchase_conversion',
    name: '购买转化率',
    icon: 'ShoppingCart',
    description: '活跃用户到付费用户的转化',
    category: 'conversion',
    categoryLabel: '转化漏斗',
    dataRequirements: '需要用户活跃记录和购买记录，能关联用户的浏览与付款行为',
    sampleQuestion: '统计最近30天活跃用户中完成首次购买的比例，按来源渠道分组对比',
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },

  // ── 运营 ──────────────────────────────────────────────────────────────────
  {
    id: 'feature_usage',
    name: '功能使用率',
    icon: 'Activity',
    description: '各功能模块的使用频率统计',
    category: 'operations',
    categoryLabel: '运营效率',
    dataRequirements: '需要包含功能名称/事件类型和使用次数的行为日志表',
    sampleQuestion: '统计各功能模块的使用次数和使用用户数，找出最受欢迎的功能',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  {
    id: 'session_analysis',
    name: '会话分析',
    icon: 'Clock',
    description: '用户平均会话时长和频率',
    category: 'operations',
    categoryLabel: '运营效率',
    dataRequirements: '需要包含会话ID、开始时间、结束时间或时长字段的会话记录表',
    sampleQuestion: '分析用户平均会话时长、每日会话次数分布，以及高峰使用时段',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  {
    id: 'peak_hour_analysis',
    name: '高峰时段分析',
    icon: 'BarChart3',
    description: '一天内各时段的用户活跃分布',
    category: 'operations',
    categoryLabel: '运营效率',
    dataRequirements: '需要包含操作时间戳的行为日志，精确到小时级别',
    sampleQuestion: '分析用户每天24小时的活跃分布，找出流量最高和最低的时段',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  {
    id: 'error_analysis',
    name: '错误/异常分析',
    icon: 'AlertTriangle',
    description: '系统错误频率和影响用户数',
    category: 'operations',
    categoryLabel: '运营效率',
    dataRequirements: '需要包含错误类型、错误时间和影响用户的错误日志表',
    sampleQuestion: '统计最近7天出现最多的错误类型TOP10，以及每种错误影响的用户数',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },

  // ── 电商 ──────────────────────────────────────────────────────────────────
  {
    id: 'order_analysis',
    name: '订单分析',
    icon: 'ShoppingCart',
    description: '订单量、GMV、客单价统计',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含订单ID、下单时间、订单金额、订单状态的订单表',
    sampleQuestion: '统计最近30天每天的订单数量、总GMV和平均客单价，展示趋势',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'repurchase_rate',
    name: '复购率分析',
    icon: 'Repeat',
    description: '用户重复购买行为分析',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含用户ID和购买时间的订单记录',
    sampleQuestion: '计算最近90天的用户复购率，以及购买次数的分布情况',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'product_performance',
    name: '商品表现',
    icon: 'Package',
    description: '各商品销量和收入排名',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含商品ID/名称、销售数量、销售金额的商品销售记录表',
    sampleQuestion: '统计销售量前10的商品，以及各商品的收入贡献占比',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'cart_abandonment',
    name: '购物车放弃率',
    icon: 'ShoppingCart',
    description: '加购后未付款的用户比例',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含用户加购行为和付款行为的事件日志，可关联用户ID',
    sampleQuestion: '分析最近30天的购物车放弃率，以及放弃率最高的商品类目',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'category_performance',
    name: '品类销售分析',
    icon: 'LayoutDashboard',
    description: '各商品品类的销量和收入占比',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含商品品类字段和销售金额的订单明细表',
    sampleQuestion: '按商品品类统计本月销售额和占比，并与上月对比变化',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'regional_sales',
    name: '区域销售分析',
    icon: 'Globe',
    description: '各地区的订单量和销售额分布',
    category: 'ecommerce',
    categoryLabel: '电商分析',
    dataRequirements: '需要包含订单收货地址或用户城市/省份字段的订单表',
    sampleQuestion: '按省份统计本季度销售额TOP10，以及各省的客单价对比',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },

  // ── 财务 ──────────────────────────────────────────────────────────────────
  {
    id: 'expense_analysis',
    name: '支出分析',
    icon: 'Receipt',
    description: '各类支出的分布和趋势',
    category: 'finance',
    categoryLabel: '财务分析',
    dataRequirements: '需要包含支出金额、支出类别和日期的财务记录或账单表',
    sampleQuestion: '按支出类别统计最近3个月的支出总额，并展示各类别的占比',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  {
    id: 'profit_trend',
    name: '利润趋势',
    icon: 'TrendingUp',
    description: '收入与支出对比，利润走势',
    category: 'finance',
    categoryLabel: '财务分析',
    dataRequirements: '需要同时包含收入和支出数据的财务表',
    sampleQuestion: '对比每月的收入和支出，计算净利润并展示利润率趋势',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  {
    id: 'payment_method',
    name: '支付方式分析',
    icon: 'DollarSign',
    description: '各支付渠道的交易量和成功率',
    category: 'finance',
    categoryLabel: '财务分析',
    dataRequirements: '需要包含支付方式、支付状态和交易金额的支付记录表',
    sampleQuestion: '统计各支付方式（微信、支付宝、银行卡等）的交易笔数、金额和支付成功率',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  {
    id: 'refund_analysis',
    name: '退款分析',
    icon: 'RefreshCw',
    description: '退款率和退款原因分布',
    category: 'finance',
    categoryLabel: '财务分析',
    dataRequirements: '需要包含退款记录、退款原因、退款金额和时间的表格',
    sampleQuestion: '分析最近30天的退款率，以及退款最多的商品品类和退款原因分布',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },

  // ── 内容流量 ──────────────────────────────────────────────────────────────
  {
    id: 'content_performance',
    name: '内容表现',
    icon: 'FileText',
    description: '文章/内容的浏览量和互动数据',
    category: 'content',
    categoryLabel: '内容流量',
    dataRequirements: '需要包含内容ID/标题、浏览量、点赞或评论数等的内容数据表',
    sampleQuestion: '统计浏览量前10的内容，并分析内容的平均互动率（点赞+评论/浏览）',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },
  {
    id: 'traffic_analysis',
    name: '流量分析',
    icon: 'Globe',
    description: '页面访问量和来源渠道分析',
    category: 'content',
    categoryLabel: '内容流量',
    dataRequirements: '需要包含页面URL、访问时间、访问来源的访问日志表',
    sampleQuestion: '分析最近7天的总PV、UV，以及流量来源（直接访问/搜索/社交媒体）分布',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },
  {
    id: 'search_keyword',
    name: '搜索词分析',
    icon: 'Search',
    description: '用户搜索行为和热门关键词',
    category: 'content',
    categoryLabel: '内容流量',
    dataRequirements: '需要包含搜索词和搜索时间的搜索日志表',
    sampleQuestion: '统计最近7天最热门的搜索词TOP20，以及零结果搜索词（用于发现内容缺口）',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },
  {
    id: 'bounce_rate',
    name: '跳出率分析',
    icon: 'LogIn',
    description: '页面跳出率和用户停留时长',
    category: 'content',
    categoryLabel: '内容流量',
    dataRequirements: '需要包含页面访问时间、停留时长或单次会话行为的访问日志',
    sampleQuestion: '统计各页面的跳出率（访问后直接离开的比例），并找出跳出率最高的落地页',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },

  // ── SaaS 指标 ─────────────────────────────────────────────────────────────
  {
    id: 'mrr_arr',
    name: 'MRR/ARR 分析',
    icon: 'TrendingUp',
    description: '月度/年度经常性收入趋势',
    category: 'saas',
    categoryLabel: 'SaaS 指标',
    dataRequirements: '需要包含订阅记录、订阅金额和订阅日期的表格',
    sampleQuestion: '统计每月的MRR（月度经常性收入）变化趋势，以及新签、扩容、流失的MRR构成',
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
  },
  {
    id: 'trial_conversion',
    name: '试用转付费率',
    icon: 'UserPlus',
    description: '免费试用用户转化为付费的比例',
    category: 'saas',
    categoryLabel: 'SaaS 指标',
    dataRequirements: '需要包含用户注册类型（试用/付费）和转化时间的用户表',
    sampleQuestion: '分析最近3个月每月的试用转付费转化率，以及从注册到付费的平均天数',
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
  },
  {
    id: 'plan_distribution',
    name: '套餐分布分析',
    icon: 'LayoutDashboard',
    description: '各价格套餐的用户数和收入占比',
    category: 'saas',
    categoryLabel: 'SaaS 指标',
    dataRequirements: '需要包含用户当前订阅套餐、套餐价格的订阅记录表',
    sampleQuestion: '统计各套餐（基础版/专业版/企业版）的订阅用户数和收入贡献占比',
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
  },
  {
    id: 'churn_mrr',
    name: 'MRR 流失分析',
    icon: 'UserMinus',
    description: '因用户流失导致的 MRR 下降',
    category: 'saas',
    categoryLabel: 'SaaS 指标',
    dataRequirements: '需要包含订阅取消记录、取消时间和订阅金额的表格',
    sampleQuestion: '分析最近6个月每月的MRR流失金额，以及主要流失原因（降级/取消）分布',
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
  },

  // ── 营销分析 ──────────────────────────────────────────────────────────────
  {
    id: 'campaign_performance',
    name: '营销活动效果',
    icon: 'Zap',
    description: '各营销活动的ROI和转化效果',
    category: 'marketing',
    categoryLabel: '营销分析',
    dataRequirements: '需要包含活动名称、活动成本、带来的用户数或订单数的营销活动记录',
    sampleQuestion: '对比各营销活动的获客成本（CAC）、带来的GMV和ROI，找出最有效的活动',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },
  {
    id: 'channel_roi',
    name: '渠道 ROI 分析',
    icon: 'BarChart3',
    description: '各营销渠道的投入产出比',
    category: 'marketing',
    categoryLabel: '营销分析',
    dataRequirements: '需要包含渠道名称、投入费用和带来的收入/用户数的渠道数据表',
    sampleQuestion: '统计各推广渠道（搜索/社交/信息流）的投入金额、带来的用户数和订单金额，计算ROI',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },
  {
    id: 'email_campaign',
    name: '邮件营销分析',
    icon: 'FileText',
    description: '邮件打开率、点击率和转化率',
    category: 'marketing',
    categoryLabel: '营销分析',
    dataRequirements: '需要包含邮件发送记录、打开状态、点击状态和转化状态的邮件日志',
    sampleQuestion: '分析最近发送的邮件营销活动的打开率、点击率和最终转化率',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },

  // ── 产品分析 ──────────────────────────────────────────────────────────────
  {
    id: 'ab_test',
    name: 'A/B 实验分析',
    icon: 'GitBranch',
    description: '实验组与对照组的效果对比',
    category: 'product',
    categoryLabel: '产品分析',
    dataRequirements: '需要包含用户分组（实验组/对照组）和关键指标的A/B实验记录',
    sampleQuestion: '对比A/B实验中实验组和对照组的转化率、人均收入，判断实验是否显著',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  {
    id: 'funnel_drop_analysis',
    name: '流程断点分析',
    icon: 'Filter',
    description: '用户在哪一步最容易放弃',
    category: 'product',
    categoryLabel: '产品分析',
    dataRequirements: '需要包含用户操作步骤和完成状态的行为日志，如注册流程、下单流程',
    sampleQuestion: '分析用户在注册流程（填写信息→验证邮箱→完善资料→首次登录）中各步的流失率',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  {
    id: 'user_segmentation',
    name: '用户分群分析',
    icon: 'Users',
    description: '按行为特征划分用户群体',
    category: 'product',
    categoryLabel: '产品分析',
    dataRequirements: '需要包含用户属性（城市/渠道/注册时间）和行为指标的综合用户表',
    sampleQuestion: '按活跃程度（高/中/低）和消费金额（高/中/低）将用户分为9个象限，统计各群体规模',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  {
    id: 'nps_analysis',
    name: 'NPS 满意度分析',
    icon: 'CheckCircle2',
    description: '净推荐值和用户满意度趋势',
    category: 'product',
    categoryLabel: '产品分析',
    dataRequirements: '需要包含用户评分（0-10分）和提交时间的NPS调查记录表',
    sampleQuestion: '计算最近一次NPS调查的净推荐值，以及推荐者/中立者/批评者的比例分布',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },

  // ── 人员管理 ──────────────────────────────────────────────────────────────
  {
    id: 'headcount_trend',
    name: '人员规模趋势',
    icon: 'Users',
    description: '员工人数的增减变化趋势',
    category: 'hr',
    categoryLabel: '人员管理',
    dataRequirements: '需要包含员工入职日期、离职日期（或在职状态）和部门的员工信息表',
    sampleQuestion: '统计每月的员工总数变化，以及各部门的人员规模对比',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
  },
  {
    id: 'attrition_rate',
    name: '人员流失率',
    icon: 'UserMinus',
    description: '员工离职率和离职原因分析',
    category: 'hr',
    categoryLabel: '人员管理',
    dataRequirements: '需要包含员工离职记录、离职时间和离职原因的人事表格',
    sampleQuestion: '计算最近12个月的员工离职率（年化），以及主要离职原因的分布',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
  },
  {
    id: 'recruitment_pipeline',
    name: '招聘漏斗分析',
    icon: 'Filter',
    description: '招聘各阶段转化率和录用周期',
    category: 'hr',
    categoryLabel: '人员管理',
    dataRequirements: '需要包含候选人申请状态、面试阶段和结果的招聘记录表',
    sampleQuestion: '分析招聘漏斗：从投递简历到最终录用各阶段的通过率，以及平均招聘周期',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
  },

  // ── 通用分析 ──────────────────────────────────────────────────────────────
  {
    id: 'data_overview',
    name: '数据概览',
    icon: 'LayoutDashboard',
    description: '表格基础统计和字段分布',
    category: 'general',
    categoryLabel: '通用分析',
    dataRequirements: '适用于任何类型的数据表，展示记录总数、字段分布等基础统计',
    sampleQuestion: '对这张表做一个基础统计概览，包括总记录数、各字段的取值分布',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  {
    id: 'time_series',
    name: '时序趋势',
    icon: 'LineChart',
    description: '任意指标随时间的变化趋势',
    category: 'general',
    categoryLabel: '通用分析',
    dataRequirements: '需要包含日期或时间字段，以及至少一个数值字段的表格',
    sampleQuestion: '按时间维度统计主要指标的变化趋势，找出波峰和波谷',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },
  {
    id: 'top_n_ranking',
    name: 'TOP N 排行',
    icon: 'BarChart3',
    description: '任意维度的TOP N排名统计',
    category: 'general',
    categoryLabel: '通用分析',
    dataRequirements: '适用于任何包含分类维度和数值指标的表格',
    sampleQuestion: '按某个维度（如城市、渠道、品类）统计数值指标的TOP10排名',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  {
    id: 'anomaly_detection',
    name: '异常数据检测',
    icon: 'AlertTriangle',
    description: '找出数据中的异常值和离群点',
    category: 'general',
    categoryLabel: '通用分析',
    dataRequirements: '需要包含数值字段的表格，通过统计方法识别异常记录',
    sampleQuestion: '检测数据中的异常值：找出订单金额、用户消费等字段中明显偏离正常范围的记录',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },
]

export function getTemplateById(id: string): AnalysisTemplate | undefined {
  return ANALYSIS_TEMPLATES.find(t => t.id === id)
}

export function getTemplatesByCategory(category: TemplateCategory): AnalysisTemplate[] {
  return ANALYSIS_TEMPLATES.filter(t => t.category === category)
}

export function getAllCategories(): TemplateCategory[] {
  return Object.keys(CATEGORY_LABELS) as TemplateCategory[]
}
